{{- if .Values.users }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-users
data:
  {{- range $key, $value := $.Values.users }}
  {{ $key }}_pass: {{ $value.password | b64enc | quote }}
  {{- end }}
{{- end }}
