apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: "tcs"
spec:
  sources:
    - useDefaultCAs: true
    - inLine: |
        -----BEGIN CERTIFICATE-----
        MIIDuTCCAqGgAwIBAgIQL2X9fWtxe49AHFNuVToBZDANBgkqhkiG9w0BAQsFADBR
        MRMwEQYKCZImiZPyLGQBGRYDQ09NMRYwFAYKCZImiZPyLGQBGRYGVENTUlNTMSIw
        IAYDVQQDExlUQ1NSU1MtQ0xPVUQtVENTUlNTLUFELUNBMB4XDTIwMDEyMDA3NTkx
        M1oXDTMwMDEyMjE2MzkzN1owUTETMBEGCgmSJomT8ixkARkWA0NPTTEWMBQGCgmS
        JomT8ixkARkWBlRDU1JTUzEiMCAGA1UEAxMZVENTUlNTLUNMT1VELVRDU1JTUy1B
        RC1DQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPdnhpAF6LlGPnLR
        bLxTABboe43tObzWSwtaNVHnnfXzTmn9MMMd/r9+3knIzft5pcksyT4qVyoeqWvU
        qlqTgk+8X+VviAxoAWsf1WAmFODYNV4JTTvdCyLbrbMmgYHfCbUTOIyzFID2mCMV
        GTSKPcZziljeu/mV9M2NC9OiXBlk9uP2ihyqgfeAs9m0ON/unZulWooTP2tNdqOg
        RiC8TwBhHeigCXjynUCAhHPmA+SaEnlYA5mt9DNO6fTzU2ml0iKODxJepid1vX3C
        OogcnI1cKXsew1KN3UsSDWa+bUAUNLV09Ou9k0z+mwqqGm56G1sAKweE+mVEMpZ6
        VuLObmcCAwEAAaOBjDCBiTATBgkrBgEEAYI3FAIEBh4EAEMAQTALBgNVHQ8EBAMC
        AYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU857mM8jyqME1kVlaVyaA7fDD
        rW4wEAYJKwYBBAGCNxUBBAMCAQEwIwYJKwYBBAGCNxUCBBYEFAKFVQzi7vSW+U+Q
        bdNjo6bk30IzMA0GCSqGSIb3DQEBCwUAA4IBAQBhpJfQPNUJsh09tseiam7+Y0eX
        r++AhKmoOn51kzS1eFqt+QIbtVFGQOYwBKZkO41yXwrbeiLXRuff5Z5t3MjmtgZD
        hVSQskDs9OLgX5WEWExLJ4pn4AVv/qR3BgrYsHEHhKLzaaNceqeWG0RNyZoq+fgm
        ArJF2ZKRnpXlBNhuHt7J5BWLm4o+v5OA+6F8Fs4vLBYtqZ4QBZ2k20VVInMMDAIw
        aGmzdsuDUhyC9Xc2v54YVJIwr4mP1OazH4YK6k0s4X7k0fW0ZW5kWOT7AqHjq0mj
        daFYR9d7V3tcHUTZy7vowr+jykMZzE0a1GPc3cCqOtduLDpboRSPHir7zudk
        -----END CERTIFICATE-----
  target:
    configMap:
      key: tcs.pem
