apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: helm-secrets-private-age-keys
data:
  key.txt: {{ $.Values.sopsAgeKeys | b64enc }}
---
{{- if $.Values.repo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: private-ssh-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ $.Values.repo.url | quote }}
  sshPrivateKey: {{ $.Values.repo.sshPrivateKey | quote }}
  insecure: {{ $.Values.repo.insecure | quote }}
  enableLfs: {{ $.Values.repo.enableLfs | quote }}
{{- end }}
---
{{- range $clusterName, $clusterValue := $.Values.clusters }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-cluster-{{ $clusterName }}
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: {{ $clusterName | quote }}
  project: {{ $clusterName | quote }}
  server: {{ $clusterValue.server | quote }}
  config: {{ $clusterValue.config | quote }}
---
{{- end }}
