#ENC[AES256_GCM,data:VJio4Ggzs83it0gp7/ysoK63U+uqYHKgIOrHKq5+6e57XUzX0REh96z29oX7LK3j2nJJlYr2+gQSX1jfnPkITD1mKfi4H6B/Cb43k13/ziXp,iv:UXNNDZ3ctOCwOMnoB76T+BuM9aTrOznzkWYC0+obYlg=,tag:5uN+MxlH239p+yS3KhbC5A==,type:comment]
#ENC[AES256_GCM,data:FHgPj4al1MDkVtJf7ZfmB2OE2WvaliAFEIGUR+z+V2r8561I9M2aavABt13QJ+vk7KH4mkl1zXBxP11e,iv:1iDtqpZ/FZVMXOys7acJ+LQ20dcAGhQccPeQDCuJL3U=,tag:YxUpy+HALx1dfiG6poc6Vw==,type:comment]
#ENC[AES256_GCM,data:p28WqfbW/Si/AZizPysJH0vQ3TywufRaLNGVY/2dImcwKmg24MSg7ZgY1EGFPpezy/lXf5Ea/KMg0fDrLTH+ugj1eNsvZWwa93pqnWeWGQkVdDocp+Atd3I=,iv:AD3IQWdZDmBRQkvd0ddnwqR7gw53eKpauq7k5chFIvY=,tag:yc+tcUZ6HZUVtm0YIesXaA==,type:comment]
#ENC[AES256_GCM,data:rT7fhtNPwJbcBvJWBRkC3leHEBK6JrniHIuVOw2fPm4VOXAMOFY9u/Q7geS0Ai/SYXd8mU5BWm9jl9fQ30NbqzRtPcswwyFav/FHesU=,iv:T9eyERjTZ/AWr5LhdznXDFJV4qqxVbuyiYhat2Zakdo=,tag:KkxUFs8ST+15FCAq5Dq7Ew==,type:comment]
#ENC[AES256_GCM,data:g2nlqnoBqk1y1ZsVqC/4Ail7DcxQG0Kj9/8YORwsB5z20SvXw8VVxpI7CZvC6SRYxVX7v2HiB5nnp+LJbBYJWdvcSL7+uYvyRYtPNg7l,iv:tNwUqxTTJbocfKb4VcBBvKs+LdwyNZTAgikazHwhoeI=,tag:KDdmVNTZ1qz3Ud+UbQnuAA==,type:comment]
#ENC[AES256_GCM,data:BY47vt7bZ0LRshExQmx8YGnT1wZuXSB7Gg7rgr8kMtPpeCXwJly528cZZepU,iv:ICUfLFdMjXzUjfJMW2WQ/c+h8uh2QnRVSk6brBNLGx0=,tag:TgWdkr7H83Oy2iKDU0yw9w==,type:comment]
k3s_server_token: ENC[AES256_GCM,data:RyU5HhrLY3v/Dzf6r+KiGLNjqb4gCK0B6+u6EF26MiE7yO3kXwykNhrWHwOJxw==,iv:bTn8dk0Nx0kVrofqrHmhFFNOXrlNZcGYGlPOFDYRUe4=,tag:y4G/FAs1QYkongeqH5UM6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5T2tlYXpXait2YnVwQ0pw
            QmVPQkhHcklYWUZQMHBDKy9VSUlyNzkydmc0CjNqYmtXSnoxNk5yMTZUaGc0SGo5
            a0xrUjNjNVJKRkhNdytOazBxUUtlUmsKLS0tIEFxMWt4T2Y0NjF2c2JTN0UyZnZG
            cU42cUJhQjFiNkxjdXJHeTh4dzYxOUEKbNY83VlEf5IgCcvyUAbwnzAioHvU2wao
            okGqXqfwXHnPCWtKWuwZt7SBhM0GvJ7KN+wCNt39nnsgtu/O/Ipavg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT09ueVlOcGpaeTFVU3A1
            M3NkVjNuVlJqYTJBREV5VWtmWEpUeUJGazIwCmR4UzE3MXdWMktuTUttaC9TR0hD
            L29VekNjcWdIMnVadmMwRFlPeUd6ZTAKLS0tICttNGlObFFpZy96b0hESEtBdkJh
            QzFQTHJuaTd0Y1VYRGhscHQ2cWZ2QUUKIMVwTYPAxfqYbtS7JLSBenqnljFup5Fr
            GKqRvkfUNlKTl3TrS3ObjliP/yTsiHUP2KVCdanO1XB0+zfgP468Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS1VLdmFmV0FEcHF6Z3pu
            c2NyZnpOM0hrK3dZVG93TTN0Yk14TlpVNFhjCmxSREZNOWJUcHRyaHdqWjNDNENP
            VlZ6d090dkc2MDI5c2dMdlBKYllUWnMKLS0tIGNZVWs4TWVNM3BQZmF6cWxyME9v
            aFBjeUpKMkhCbXEvUmIvNHZiSU9VcVkKxT5tRK/jQEwVlc1aFzOLR/GYLhxrmQgS
            a2ycvFdGm1IGgqKl94/ltdOQ6iSNMS8X0goel3g2NeKGp8OPxuB+iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138ut93gvvwkaudl3wxtwn8z9e50ptuhe2yukg6vhwcgncxpplpsqtmhp7t
    lastmodified: "2025-08-28T10:57:54Z"
    mac: ENC[AES256_GCM,data:beJ3wnp9h7Dc/HYuncETwKd8Nk25DNMtTDI27XrRhUaX1QX1UELoiUkpjyZtJmzK+bHuvFQLkcVrUODbRjuJi7OF85we6qC3Vp818cYODicS1sMUkeR2X8YfULpX/RDcaGin8MgqYijJRjg+yUdLQQJWNr5Venc9l0QhnMTFKis=,iv:19YGPv4sR+0+Tkpz4pnOaqO0hjbQ4nSzRkGdB3NyTCc=,tag:mYOdVF5uaj8kkw+rejFR5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
