apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: keycloak-db
data:
  username: {{ $.Values.postgres.username | b64enc | quote }}
  password: {{ $.Values.postgres.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: keycloak-admin
data:
  username: {{ $.Values.username | b64enc | quote }}
  password: {{ $.Values.password | b64enc | quote }}
---
{{- range $key, $val := $.Values.registries }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: {{ $key }}
data:
  {{- $auth := printf "%s:%s" .username .password | b64enc }}
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" $key $auth | b64enc }}
---
{{- end }}
