{{- range $user, $value := .Values.users }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: "cnpg-user-{{ $user }}"
  labels:
    cnpg.io/reload: "true"
data:
  username: {{ $user | b64enc | quote }}
  password: {{ $value.password | b64enc | quote }}
---
{{- end -}}
