apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-novu-externals3
data:
  endpoint: {{ $.Values.externalServices.s3.endpoint | b64enc }}
  bucketName: {{ $.Values.externalServices.s3.buckets.novu | b64enc }}
  region: {{ "us-east-1" | b64enc }}
  accessKey: {{ $.Values.externalServices.s3.auth.accessKey| b64enc }}
  secretKey: {{ $.Values.externalServices.s3.auth.secretKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-novu-externalredis
data:
  redis-password: {{ $.Values.externalServices.valkey.password | b64enc }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-embed"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-embed"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-embed"
    spec:
      containers:
      - name: embed
        image: "registry.bud.studio/novu/embed:0.24.0"
        ports:
        - containerPort: 4701
        env:
          - name: REDIS_HOST
            value : {{ $.Values.externalServices.valkey.host | quote }}
          - name: REDIS_PORT
            value : {{ $.Values.externalServices.valkey.port | quote }}
          - name: REDIS_DB_INDEX
            value : {{ $.Values.externalServices.valkey.databases.novu | quote }}
          - name: REDIS_PASSWORD
            value : "{{ .Values.externalServices.valkey.password }}"
          - name: MONGO_URL
            value: "mongodb://{{ $.Values.externalServices.mongodb.auth.username }}:{{ $.Values.externalServices.mongodb.auth.password }}@{{ $.Values.externalServices.mongodb.endpoint }}/{{ $.Values.externalServices.mongodb.databases.novu }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-embed"
spec:
  ports:
  - protocol: TCP
    port: 4701
    targetPort: 4701
  selector:
    app: "{{ .Release.Name }}-embed"
