replsetSize: 3
image: "percona/percona-server-mongodb:8.0.19-7"
imagePullPolicy: "Always"
storage:
  size: 4Gi
  className: ""

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: mongod
              app.kubernetes.io/replset: rs0
        weight: 100

users: {}

psmdb-operator:
  enabled: true
