storage:
  className: "openebs-lvm"

users:
  monitoring:
    password: monitoring
    roles:
      - name: clusterMonitor
        db: admin
  bud_novu_sinan:
    db: bud_novu_sinan
    password: bud_novu
    roles:
      - name: dbOwner
        db: bud_novu_sinan
