sopsAgeKeys: ENC[AES256_GCM,data:zx0okMjClLp3AADmtMDudTpN/9ClXd+pawwMtxG1tHD47rzZPkpHtwt08VytRt5YZHsdpDeG5OzlFGbfd39AMteE7CoO2KqlILCO1dc6VPFecfUAZwQl9+Lad9GpFEeLbzqycN7Pf7DnJnVfREKoRB+RLT1IOo1UAFzv0xfgUePE+6O2B6+6bB/LFFCbPz3tHtlioYfXAHG9npiFHYpvBG8AJyfRq54oAJm6n5eHmazGCbxvt7HwGzgnoFo=,iv:CMMLaah1DcpHrLd1oWoKAOTPNwchkAlqMfJI0aYqEGs=,tag:p9pURiVC1DDtlm22RYInOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTDd1aXV0c2NIZG5PMVNG
            WVJYOG5lMmcydFdVeUUrZS9SNEVsVXNNdzFNCkpvOEJPSlVBeWFjdXo4a0ZYOVFL
            cUNpY3oxVS9uVENodURTUmdCS2RSVGcKLS0tIEFLd0hEb0R6NVpjUWl0US9OMDd3
            UlB4THdxalNCaDB2bWQwZkM4TGUvczgKfBNNk1nGFXvlJ/5s8CBDJD2Bemup7QL/
            24FtPwYvgUdbfAd4aVp0elUfnBJHDEUdbfZL+G3xZEI3L+NT3HFkSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S2JBLzE0Rk9OdWVhZ3Jq
            dVMwT1dLTkNOSFJZVm4zbWxQT2N4Z3d0RVN3CkFLN3FmZlhnTUcrUSs2UkZmREFK
            NGNWVjZFNTNQTTlnZUVxNzlqS2RqQ0kKLS0tIFYrNjQxTWhOM3NiSkNFNXo4eUN6
            cGt1T2wwQ3ZkNnpoaGN1b2tnNkowYUkKb2eJsQzE38tUT6gdW1nXbTVWlZb5SVFt
            aV97tlfbMeH0PYnTvB4RNaMh9+X9/yq9p6jdOoIuF0iqpW65fhhH3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hux3h87h0480ss493kl292alfe6m6z5dhe76phvuk2c82hvg9clqmp6d8d
    lastmodified: "2026-07-30T09:03:41Z"
    mac: ENC[AES256_GCM,data:htjMpFhwXDgTSvv6ZzvUVLdKPisuDm1ky9Pal7Mevnn9BnzsvUHpVALl96RzTUJFofzezTZ1swc9fYS1dLGwCVE2gPV4bOSPlu3qdg2ULqbQYzmfW02eHZ/N4D/hMU+rZlhyKJbp7KIDifaqIb7iwXKW5ztYOSoeadeJIienZwM=,iv:V71vI5HpjAP8lhPFWnnpQGoNB2oKu9M2Lh72eHqMDhU=,tag:bq+LeE3VCX4tRZ+hguZe2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
