{{- if $.Values.keeper.enabled }}
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: clickhouse-keeper
spec:
  configuration:
    clusters:
      - name: chk01
        layout:
          replicasCount: 3

  defaults:
    templates:
      podTemplate: default
      volumeClaimTemplate: keeper-storage

  templates:
    podTemplates:
      - name: default
        metadata:
          labels:
            app: clickhouse-keeper
        spec:
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: IfNotPresent
              image: {{ $.Values.keeper.image | quote }}
          {{- with $.Values.keeper.affinity }}
          affinity:
            {{- . | toYaml | nindent 14 }}
          {{- end }}
          securityContext:
            fsGroup: 101

    volumeClaimTemplates:
      - name: keeper-storage
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ $.Values.keeper.size }}
          {{- with $.Values.keeper.storageClass }}
          storageClassName: {{ . | quote }}
          {{- end }}
{{- end }}
