{{- range $key, $val := $.Values.registries }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: {{ $key }}
data:
  {{- $auth := printf "%s:%s" .username .password | b64enc }}
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" $key $auth | b64enc }}
---
{{- end }}
