users:
  bud:
    password: "bud"
    spec: {}

strimzi-kafka-operator:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 75
          preference:
            matchExpressions:
              - key: bud.studio/control-plane
                operator: In
                values:
                  - "true"
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 75
        preference:
          matchExpressions:
            - key: bud.studio/control-plane
              operator: In
              values:
                - "true"
