apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Release.Name }}-secretstore
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-secretstore
type: Opaque
data:
  openai_token: ""

  redis_secret_uri: {{ printf "%s:%s" $.Values.externalServices.valkey.host $.Values.externalServices.valkey.port | b64enc | quote }}
  REDIS_URI: {{ printf "%s:%s" $.Values.externalServices.valkey.host $.Values.externalServices.valkey.port | b64enc | quote }}
  redis_secret_password: {{ $.Values.externalServices.valkey.password | b64enc | quote }}
  REDIS_PASSWORD: {{ $.Values.externalServices.valkey.password | b64enc | quote }}

  novu_credentials_email: {{ $.Values.novuExtra.email | b64enc | quote }}
  novu_credentials_password: {{ $.Values.novuExtra.password | b64enc | quote }}

  MINIO_ACCESS_KEY: {{ $.Values.externalServices.s3.auth.accessKey | b64enc | quote }}
  MINIO_SECRET_KEY:  {{ $.Values.externalServices.s3.auth.secretKey | b64enc | quote }}
  CLICKHOUSE_USER: {{ $.Values.externalServices.clickhouse.auth.username | b64enc | quote }}
  CLICKHOUSE_PASSWORD: {{ $.Values.externalServices.clickhouse.auth.password | b64enc | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-dapr-secret-reader
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: {{ .Release.Name }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
