ingress:
  enabled: false
  https: false
  host: example.com

volumeServerDiskCount: 1
image: chrislusf/seaweedfs:4.33
storageClassName: ""

volumePvcSize: "64Gi"
volumeSizeLimitMB: 10000
defaultReplication: "000"
replicas:
  master: 3
  worker: 2
  filer: 2
  s3: 2
  volume: 2

volumeTopology: {}
affinity: {}

postgres:
  image: "ghcr.io/cloudnative-pg/postgresql:17.9"
  host: "pooler-rw.postgres"
  port: 5432
  username: "seaweedfs"
  password: "seaweedfs"
  database: "seaweedfs"

seaweedfs-operator:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    tag: "1.0.25"
  grafanaDashboard:
    enabled: false

buckets: {}
identity: {}
policy: {}
