enabled: true
global:
  ha:
    enabled: false
dapr_scheduler:
  ha: true
  cluster:
    storageSize: "1Gi"
    storageClassName: ""
dapr_placement:
  ha: true
  volumeclaims:
    storageClassName: ""
