{{- if (default .Values.microservices.budadmin.enabled false) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-budadmin
  annotations:
    {{- range $key, $value := .Values.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if not (and .Values.microservices.budadmin.autoscaling .Values.microservices.budadmin.autoscaling.enabled) }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-budadmin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-budadmin
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $nodeSelector := include "bud.nodeSelector" (dict "service" .Values.microservices.budadmin "global" .Values.global "context" $) }}
      {{- if $nodeSelector }}
      nodeSelector:
        {{- $nodeSelector | nindent 8 }}
      {{- end }}
      {{- $affinity := include "bud.affinity" (dict "service" .Values.microservices.budadmin "global" .Values.global "context" $) }}
      {{- if $affinity }}
      affinity:
        {{- $affinity | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}-budadmin
        image: {{ .Values.microservices.budadmin.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 3000
        env:
          - name: ENTRYPOINT_BUDNOTIFY_SERVICE
            value: "{{ .Release.Name }}-budnotify:3000"
          - name: NEXT_PUBLIC_PASSWORD
            value: {{ .Values.microservices.rsaKeys.privateKeyPassword }}
          - name: NEXT_PUBLIC_PRIVATE_KEY
            value: {{ .Values.microservices.rsaKeys.privateKey | b64enc }}
          - name: BASE_URL
            value: {{ include "bud.ingress.url.budapp" $ }}
          - name: NEXT_PUBLIC_BASE_URL
            value: {{ include "bud.ingress.url.budapp" $ }}
          - name: NEXT_PUBLIC_TEMP_API_BASE_URL
            value: {{ include "bud.ingress.url.budapp" $ }}
          - name: NEXT_PUBLIC_NOVU_SOCKET_URL
            value: {{ include "bud.ingress.url.novuws" $ }}
          - name: NEXT_PUBLIC_NOVU_BASE_URL
            value: {{ include "bud.ingress.url.novuapi" $ }}
          - name: NEXT_PUBLIC_COPY_CODE_API_BASE_URL
            value: {{ include "bud.ingress.url.budgateway" $ }}/
          - name: NEXT_PUBLIC_PLAYGROUND_URL
            value: {{ include "bud.ingress.url.budplayground" $ }}
          - name: NEXT_PUBLIC_ASK_BUD_URL
            value: '{{ include "bud.ingress.url.budask" $ }}/v1'
          - name: NEXT_PUBLIC_ASK_BUD_MODEL
            value: {{ .Values.microservices.askbud.model }}
          - name: NEXT_PUBLIC_BUDNOTIFY_SERVICE_PUBLIC
            value: {{ include "bud.ingress.url.budnotify" $ }}
        {{ $root := . }}
        {{- range $key, $value := .Values.microservices.budadmin.env }}
          - name: {{ $key }}
            value: {{ tpl $value $root | quote }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name}}-bud-global
        {{- with .Values.microservices.budadmin.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-budadmin
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: {{ .Release.Name }}-budadmin
  type: ClusterIP
{{- if and .Values.microservices.budadmin.autoscaling .Values.microservices.budadmin.autoscaling.enabled }}
---
{{- include "bud.hpa" (dict "serviceName" "budadmin" "Values" .Values "Release" .Release) }}
{{- end }}
{{ end }}
