trust-manager:
  enabled: false

cert-manager:
  enabled: true
  crds:
    enabled: true
  ingressShim:
    defaultIssuerName: letsencrypt-http01
    defaultIssuerKind: ClusterIssuer
    defaultIssuerGroup: cert-manager.io

secrets: {}
certificates: {}
bundles: {}

issuers:
  letsencrypt-http01:
    acme:
      profile: tlsserver
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: letsencrypt-http01-account-key
      solvers:
        - http01:
            ingress:
              ingressClassName: traefik
