clusterPolicies:
  inject-selfsigned-ca:
    background: false
    rules:
      - name: inject-selfsigned-ca
        match:
          any:
            - resources:
                namespaces:
                  - bud
                kinds:
                  - Pod
        mutate:
          foreach:
            - list: request.object.spec.containers
              patchStrategicMerge:
                spec:
                  volumes:
                    - name: selfsigned-with-default-ca
                      configMap:
                        name: selfsigned-with-default-ca
                  containers:
                    - name: "{{ element.name }}"
                      volumeMounts:
                        - name: selfsigned-with-default-ca
                          mountPath: /etc/ssl/certs/selfsigned-with-default-ca.pem
                          subPath: selfsigned-with-default-ca.pem.pem
                          readOnly: true
                      env:
                        - name: SSL_CERT_FILE
                          value: "/etc/ssl/certs/selfsigned-with-default-ca.pem"
                        - name: NODE_EXTRA_CA_CERTS
                          value: "/etc/ssl/certs/selfsigned-with-default-ca.pem"
                        - name: REQUESTS_CA_BUNDLE
                          value: "/etc/ssl/certs/selfsigned-with-default-ca.pem"
