altinity-clickhouse-operator:
  enabled: true

image: altinity/clickhouse-server:26.1.11.20001.altinityantalya
storageClass: ""
size: 8Gi
reclaimPolicy: Retain # (Retain|Delete)
replicaCount: 3

keeper:
  enabled: true
  image: altinity/clickhouse-keeper:26.1.11.20001.altinityantalya
  storageClass: ""
  size: 1Gi

users: {}
resources: {}
configuration:
  settings: {}
  profiles: {}
